language: ruby
node_js:
  - "7.4"

cache:
  bundler: true
  directories:
    - node_modules

bundler_args: --path .cache

before_install:
  - npm i
  - gem install sass

script:
  - npm test

sudo: false

notifications:
  email: false
